const Actions = {
  PEXEL_BAY_ACTIONS_GET_DATA: "PEXEL_BAY_ACTIONS_GET_DATA",
  PEXEL_BAY_ACTIONS_GET_DATA_SUCCESS: "PEXEL_BAY_ACTIONS_GET_DATA_SUCCESS",
  PEXEL_BAY_ACTIONS_GET_DATA_FAILURE: "PEXEL_BAY_ACTIONS_GET_DATA_FAILURE",
  GET_SELECTED_DATA: "GET_SELECTED_DATA",
  GET_SELECTED_DATA_SUCCESS: "GET_SELECTED_DATA_SUCCESS",
  GET_SELECTED_DATA_FAILURE: "GET_SELECTED_DATA_FAILURE",
};

export default Actions;
