const Actions = {
    SET_CONTAINER_LISTING : 'SET_CONTAINER_LISTING',
    SET_CONTAINER_LISTING_SUCCESS : 'SET_CONTAINER_LISTING_SUCCESS',
    SET_CONTAINER_LISTING_FAILURE : 'SET_CONTAINER_LISTING_FAILURE',
    SET_LISTING_CONTAINER_NUMBER: 'SET_LISTING_CONTAINER_NUMBER',
    SET_LISTING_CONTAINER_NUMBER_SUCCESS: 'SET_LISTING_CONTAINER_NUMBER',
    SET_LISTING_CONTAINER_NUMBER_FAILURE: 'SET_LISTING_CONTAINER_NUMBER',
}

export default Actions